package common

const (
	//=======Cache=======
	CACHE_ADMIN 	= "MXADMIN:"
	CACHE_MENU		= "CACHE_MENU"
	CACHE_ADMINROLEPRIV = "CACHE_ADMINROLEPRIV"
	CACHE_ARTICLE 	= "MXARTICLE:"
	CACHE_TAG     	= "MXTAG:"


	//=======Error=======
	ERROR_GET_USER_ADMIN_FAIL 	= "ERROR_GET_USER_ADMIN_FAIL"
	ERROR_NOT_EXIST_USER_ADMIN 	= "ERROR_NOT_EXIST_USER_ADMIN"
	ERROR_GET_MENU_FAIL 		= "ERROR_GET_MENU_FAIL"
)
